# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Borana Dollomaja
title: Computational Neuroscientist, Postdoctoral researcher at the Systems Neuroscience Institute - Aix-Marseille University
email: boranadollomaja at gmail dot com
website: https://balancekey.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: boranadll
github_username:  BalanceKey
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: bod
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0003-3069-5838

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/my_image.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Borana and I'm currently a PostDoctoral researcher in Computational Neuroscience.
  I am well used to working within an interdisciplinary team, where theoreticians, programmers, biologists and clinicians come together to provide innovative approaches to health and diagnostics.
  My work has also taught me autonomy, adaptability and perserverance.

  I recently obtained my PhD in "Modelling brain stimulation for drug-resistant epilepsy", where I used individualized Virtual Brain Models to study brain stimulation in epilepsy.
  I have solid knowledge in computer science and applied mathematics, where I obtained an engineering degree in Grenoble INP - ENSIMAG.

  I love applying mathematics to physical and biological phenomena, in particular for health and clinical applications ! I also am amazed by the brain and what it can do.

  I am most skilled in: <mark>Programming</mark>, <mark>Brain imaging</mark>, <mark>Modelling</mark> and <mark>Simulations</mark>.
#
content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Virtual epileptic patient cohort
#        link: github.com/BalanceKey/virtual_epilepsy_patient_cohort
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/BalanceKey/virtual_epilepsy_patient_cohort
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          Building virtual brain twins and simulated brain activity of real patients with drug-resistant epilepsy
#        description: | # this will include new lines to allow paragraphs
#          The goal of this project was to build a synthetic copy of an empirical dataset of 30 patients with drug-resistant epilepsy.
##          People with drug-resistant epilepsy suffer from intractable seizures and can be treated with brain surgery.
##          Their chance of becoming seizure-free heavily relies on proper diagnosis of brain regions responsible for seizure generation, known as epileptogenic zones (EZ).
##          In the clinic, empirical recordings of brain activity are used to estimate these brain regions.
##          However, the underlying ground truth is not available.
##          We built a virtual cohort of 30 patients with drug-resistant epilepsy, using individual patients’ data to simulate their epileptic brain activity.
##          This brain modeling based on personalized data is referred to as a virtual brain twin.
##          The key parameters of these virtual brain twins including the EZ settings serve as the ground-truth.
##          Epileptic brain activity is simulated at the whole-brain level and mapped onto intracranial sensors to mimic real recordings. We quantified how well the synthetic signal captured features from the empirical data.
##          For each virtual brain twin, we generated spontaneous seizures, stimulated seizures and interictal activity.
##          This cohort is made available to the scientific community to benchmark methods such as estimation of EZ and source localization.
##
#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: Theoretical Neuroscience Group - Institut de Neurosciences des Systemes
#        link: ins-amu.fr
#        # link_text: boringcompany.com
#        sub_title: Postdoctoral Researcher
#        caption: January 2025 - Present
#        quote: >
#          Using virtual brain twins to predict brain stimulation responses in-silico.
#        description: | # this will include new lines to allow paragraphs
#          Following my PhD thesis work, I am continuing to use individualized virtual brain models to predict stimulation response in drug-resistant epilepsy. Here, I am using brain imaging data to parametrize the virtual brain twins and performing simulations to compare the outcome to the empirical data. Using a <mark>genetic algorithm</mark> approach, I am estimating the parameters of the virtual brain twin that can predict the empirical data.
##      - layout: left
##        title: Theoretical Neuroscience Group - Institut de Neurosciences des Systemes
##        link: https://ins-amu.fr/
##        # link_text: boringcompany.com
##        sub_title: PhD candidate
##        caption: May 2021 - December 2024
##        quote: >
##          Modeling brain stimulation for diagnosis of drug-resistant epilepsy
##        description: | # this will include new lines to allow paragraphs
##          I completed a PhD in Computational Neuroscience, using virtual brain models to diagnose drug-resistant epilepsy.
##          My project was focused on modelling the effects of <mark>brain stimulation</mark> in epilepsy, in particular when triggering seizures.
##          To this end, I extended an existing model to account for brain stimulation effects in seizure generation in epilepsy, which I tested and validated in a synthetic cohort of 30 patients with drug-resistant epilepsy.
##          In addition, the modelling framework was extented for high-resolution virtual brain models and non-invasive stimulation, demonstrating a potential methodology for purely <mark>non-invasive diagnosis</mark> of drug-resistant epilepsy.
##
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aix-Marseille University
        caption: 2021 - 2024
        sub_title: PhD in Neuroscience
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my PhD at Aix-Marseille University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
#          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
